export const siteUrl = "https://tarot-by-leona.netlify.app";
export const keywords = [
  "tarot",
  "astro",
  "tarot and astro services",
  "leona",
  "divination",
  "divine",
  "astrology",
  "oracle",
  "cosmic guidance",
  "78 cards",
  "guidance",
  "reading",
  "future",
  "heavenly bodies",
  "birth chart",
  "natal chart",
  "personal growth",
  "session",
  "cherry blossom agate",
  "dream amethyst",
  "garnet",
  "golden obsidian",
  "green aventurine",
  "red eyes tiger",
  "rose quartz",
];
